### ISSUE TITLE
java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.Thread.isAlive()' on a null object reference

### ISSUE THREAD

**Issue by chariotsystems** [bluecats/bluecats-android-sdk#10]
We get 30 crashes like this every day.
Crashed Thread

0	java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.Thread.isAlive()' on a null object reference
!	1	at com.bluecats.sdk.ao.y(SourceFile:229)
2	at com.bluecats.sdk.ao.a(SourceFile:223)
3	at com.bluecats.sdk.ao$2.run(SourceFile:393)
4	at java.lang.Thread.run(Thread.java:818)

The reason for the crash and possible fix is easy:
private void y() {
        if(i != null) {
            Log.d("BlueCatsBLEScheduledScanner", "Interrupt scan schedule thread");
            i.interrupt();

            while(i.isAlive()) {
                try {
                    Thread.sleep(10L);
                } catch (InterruptedException var1) {
                    Log.e("BlueCatsBLEScheduledScanner", "mScanScheduleRestartProcessor interrupted");
                }
            }

            i = null;
        }

        if(i == null) {
            this.e(true);
            Log.d("BlueCatsBLEScheduledScanner", "Restart new scan schedule thread");
            (i = new Thread(this.l, "ScanScheduleQueueProcessor")).setPriority(1);
            i.start();
        } else {
            this.v();
        }
    }

The while(i.isAlive()) { should be changed to while(i != null && i.isAlive() 

The reason is that i gets set to null in g()
   public final void g() {
        if(this.b()) {
            Log.d("BlueCatsBLEScheduledScanner", "stopScanning");
            this.n();
            this.e(false);
            this.f(false);
            this.d(false);
            if(i != null) {
                i.interrupt();
            }

            if(j != null) {
                j.interrupt();
            }

            while(i != null && i.isAlive() || j != null && j.isAlive()) {
                try {
                    Thread.sleep(10L);
                } catch (InterruptedException var1) {
                    Log.e("BlueCatsBLEScheduledScanner", "stopScanning interrupted");
                }
            }

            i = null;
            j = null;
            this.r();
            this.p();
            this.a(false);
        }

    }

**Comment by henrybluecats** [comment]
hi chariotsystems,
we have identified this issue, and will publish a new release early next week.
Thanks for your feedback.

**Comment by chariotsystems** [comment]
That's great.
Thanks
Alex

**Comment by chariotsystems** [comment]
Hi Henry,
Do you have the list of fixes that will be included in the new jar?
The other rather annoying crashes that are caused by bluecats are:
java.lang.SecurityException: Client must have ACCESS_COARSE_LOCATION or ACCESS_FINE_LOCATION permission to perform any location operations.
and
java.lang.IllegalStateException
BT Adapter is not turned ON

In both cases if bluecats had simply disabled the scan that would have been a far better user experience for our users.  The bluecats feature is a nice to have for our app and for bluecats to crash the app when our customers device is not supporting bluecats or gps is a little 'over the top'.

Cheers
Alex

**Comment by henrybluecats** [comment]
Hi Alex,
Could you send the logcat to me (henry@bluecats.com) about the crashes related to location services and bluetooth?

Thanks,
Henry

**Comment by jcw9967** [comment]
Hey Alex!

The exceptions you're experiencing are abnormal and most likely bugs. We do have measures in place to ensure the SDK has permission to perform operations before it does them, and certainly shouldn't be using the bluetooth adapter if it's not turned on, so you've found some very interesting bugs.

We don't have a definite list of bugs fixed at this point, but if you send the crash logs over to Henry we'll be happy to have a look at them!

**Comment by henrybluecats** [comment]
Hey Alex,
we have fixed this issue in release v2.0.1
