### ISSUE TITLE
BlueCatsSDKService stops tracking after a few days

### ISSUE THREAD

**Issue by Tuccro** [bluecats/bluecats-android-sdk#13]
I'm using BlueCatsSDK in custom Android Service as it described at [example](https://github.com/bluecats/bluecats-services-android/blob/master/app/src/main/java/com/bluecats/services/interfaces/BlueCatsSDKInterfaceService.java).

BlueCatsSDKService stops tracking after a few days.

My own service that uses BlueCatsSDK works correctly (I can see it by web requests that it sends periodically to my server).

The issue seems the same as described here - https://forums.estimote.com/t/monitoring-stops-in-background-after-few-hours/3099/11

Devices: Samsung SM-G930F (Android 6.0.1, 7.0), Xiaomi Mi3 (Android 6.0.1)

**Comment by theporkchopexpress** [comment]
hey tuccro, are you leaving your devices idle for a few days, or are you just noticing the BlueCatsSDKService stopping tracking in general use? are your devices connected or disconnected, or a mixture? 

also, is there any sample code you can share that we can test against ourselves? 

cheers,
darren

**Comment by Tuccro** [comment]
Hi, seems that it is OS issue, not SDK. We found a workaround and testing it right now. Thank you.

**Comment by theporkchopexpress** [comment]
ok, thats good news. would you mind sharing your findings if you are able to resolve the issue? we'd be interested to know what caused this and how you were able to workaround it.

cheers,
darren
