### ISSUE TITLE
Can't get purring on Android

### ISSUE THREAD

**Issue by alg** [bluecats/bluecats-android-sdk#16]
Hi guys,

I'm writing a module for our NativeScript project and facing a strange thing. iOS part works just fine, but when it comes to Android, I seem can't get it to start.

I registered two apps in my https://app.bluecats.com/apps and got tokens. Tripple-verified they are correct. When I do the following:

    BlueCatsSDK.startPurringWithAppToken(ctx, token);

I get BC_STATUS_STOPPED_PURRING and BC_APP_TOKEN_VERIFICATION_STATUS_NOT_PROVIDED

Then, if I do this:

    BlueCatsSDK.setAppToken(token);
    BlueCatsSDK.startPurring(ctx);

I strangely get BC_STATUS_STOPPED_PURRING but this time BC_APP_TOKEN_VERIFICATION_STATUS_NOT_VERIFIED.

I'm testing on the real device (Google Pixel) connected to the network through wifi.

Any (even wildest) assumptions as to what can be wrong?
Should I be running the service?
Should I notify the SDK that the app has resumed (when starting)?

Cheers,
- Aleks

**Comment by henrybluecats** [comment]
Hi Aleks,
I recommend to use BlueCatsSDK.startPurringWithAppToken(ctx, token); in Activity or Service. The error BC_APP_TOKEN_VERIFICATION_STATUS_NOT_PROVIDED indicated app token was missing. 
Have you run this demo app https://github.com/bluecats/bluecats-scratchingpost-android by replacing your own app token in the source code.
If you are still facing the issue, could you send me your project skeleton with that I can run and look deeply into for you.

Thanks,
Henry

**Comment by alg** [comment]
Thanks, Henry. Yes, I tried it both ways and received different errors. When I tried `startPurringWithAppToken` it returned `_NOT_PROVIDED`. If I set the token with `setAppToken`, it returned `_NOT_VERIFIED`.

I took my code from the demo app. Will build it now with my token.

**Comment by alg** [comment]
@henrybluecats Sorry for the late answer. I get exactly the same two responses depending on whether I set app token with additional call or no with the demo app. Here's how I updated the SitesActivity.java:

    // If I add this line, I'm  getting BC_APP_TOKEN_VERIFICATION_STATUS_NOT_VERIFIED.
    // If I comment it, I'm getting BC_APP_TOKEN_VERIFICATION_STATUS_NOT_PROVIDED
    BlueCatsSDK.setAppToken(Constants.BLUECATS_APP_TOKEN); 

    BlueCatsSDK.startPurringWithAppToken( getApplicationContext(), Constants.BLUECATS_APP_TOKEN );

    BlueCatsSDK.BCAppTokenVerificationStatus status =
        BlueCatsSDK.getAppTokenVerificationStatus();
    Log.i("SitesActivity", "Token verification status:" + status);

I wonder if I should wait for the initialization completion (`startPurringWithAppToken`) before checking for the verification status?

**Comment by henrybluecats** [comment]
Hi alg,
BlueCatsSDK.startPurringWithAppToken is an asynchronous method, so you should check the status later in a Handler or thread.

**Comment by alg** [comment]
@henrybluecats I expected so, but couldn't find any callbacks in the API. Are there any or I should just schedule the timer and check every 3 seconds?

**Comment by henrybluecats** [comment]
you may call BlueCatsSDK.getStatus() periodically to check the status. once you get BCStatus.BC_STATUS_PURRING returned, the SDK is running properly.
