### ISSUE TITLE
Beacon Event not occured 

### ISSUE THREAD

**Issue by bhushanvyas** [bluecats/bluecats-android-sdk#18]
In Android  >=7.0 we didn't get ant call back of beacon while same code is working on android 5.0.
We already provide location permission even we check same code on 6.0 code working fine, problem arries from 7.0 and above version.
Please let me know is any extra add on or changes are require for this version of OS .
Thanks

**Comment by theporkchopexpress** [comment]
I am marking this issue to be closed. Please comment if you would like further support.

Cheers,
Darren

**Comment by theporkchopexpress** [comment]
Closing issue
