### ISSUE TITLE
Gradle

### ISSUE THREAD

**Issue by ademar111190** [bluecats/bluecats-android-sdk#2]
When the bluecats SDK will be available on maven to use with gradle on Android Studio?

**Comment by darren-bluecats** [comment]
Hi,

sorry for the really late reply to this. To be honest we dont actually have a date for putting the SDK on to maven as yet. We are currently using the restlet framework for our HTTP stuff and I think we would like to move away from this framework and inhouse the network code before putting up on maven as restlet have their own maven repository, they dont use the central maven repository. 

Can you think of any problems with using restlet over maven?

http://restlet.com/technical-resources/restlet-framework/guide/2.3/introduction/getting-started/maven

Cheers,
Darren
