### ISSUE TITLE
Bluecats is crashing and looks like not ready for Android 12. 

### ISSUE THREAD

**Issue by bm185178** [bluecats/bluecats-android-sdk#23]
10-13 01:17:01.638 22980 22980 E AndroidRuntime: java.lang.RuntimeException: Unable to create service com.bluecats.sdk.BlueCatsSDKService: java.lang.IllegalArgumentException: <packageId>: Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.
10-13 01:17:01.638 22980 22980 E AndroidRuntime: Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent being mutable, e.g. if it needs to be used with inline replies or bubbles.
10-13 01:17:01.638 22980 22980 E AndroidRuntime:        at android.app.ActivityThread.handleCreateService(ActivityThread.java:4504)
10-13 01:17:01.638 22980 22980 E AndroidRuntime:        at android.app.ActivityThread.access$1700(ActivityThread.java:247)
10-13 01:17:01.638 22980 22980 E AndroidRuntime:        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2076)
10-13 01:17:01.638 22980 22980 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:106)
10-13 01:17:01.638 22980 22980 E AndroidRuntime:        at android.os.Looper.loopOnce(Looper.java:201)
10-13 01:17:01.638 22980 22980 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:288)
10-13 01:17:01.638 22980 22980 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:7842)
10-13 01:17:01.638 22980 22980 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
10-13 01:17:01.638 22980 22980 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
10-13 01:17:01.638 22980 22980 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
10-13 01:17:01.638 22980 22980 E AndroidRuntime: Caused by: java.lang.IllegalArgumentException: <packageId>: Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.
10-13 01:17:01.638 22980 22980 E AndroidRuntime: Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent being mutable, e.g. if it needs to be used with inline replies or bubbles.
10-13 01:17:01.638 22980 22980 E AndroidRuntime:        at android.app.PendingIntent.checkFlags(PendingIntent.java:375)
10-13 01:17:01.638 22980 22980 E AndroidRuntime:        at android.app.PendingIntent.buildServicePendingIntent(PendingIntent.java:724)
10-13 01:17:01.638 22980 22980 E AndroidRuntime:        at android.app.PendingIntent.getService(PendingIntent.java:686)
10-13 01:17:01.638 22980 22980 E AndroidRuntime:        at a.a.a.b1.<init>(SourceFile:286)
10-13 01:17:01.638 22980 22980 E AndroidRuntime:        at a.a.a.e1.<init>(SourceFile:1)
10-13 01:17:01.638 22980 22980 E AndroidRuntime:        at a.a.a.d1.<init>(SourceFile:1)
10-13 01:17:01.638 22980 22980 E AndroidRuntime:        at com.bluecats.sdk.BlueCatsSDKService.onCreate(SourceFile:29)
10-13 01:17:01.638 22980 22980 E AndroidRuntime:        at android.app.ActivityThread.handleCreateService(ActivityThread.java:4491)
10-13 01:17:01.638 22980 22980 E AndroidRuntime:        ... 9 more

**Comment by UbiPark-dev** [comment]
@bm185178 We're encountering the same error with our app when attempting to target Android 12. Have you come up with a workaround/fix?

**Comment by henrybluecats** [comment]
@bm185178 @UbiPark-dev Hi, we've uploaded a new SDK v2.1.8 to support Android 12, Please check it out at https://repo1.maven.org/maven2/com/bluecats/bluecats-android-sdk/ or in your build.gradle add dependency "implementation 'com.bluecats:bluecats-android-sdk:2.1.8' "
