### ISSUE TITLE
BCEvent missing method for obtaining category name

### ISSUE THREAD

**Issue by JrGoodle** [bluecats/bluecats-android-sdk#7]
While exploring the iOS and Android SDK's, another engineer and I came across what appears to be a mismatch between the SDK's on the different platforms. The `BCEvent` class in the iOS SDK has a `categoryName` property for obtaining the name of the category of a triggered event. However, the `BCEvent` class in the Android SDK doesn't have a `getCategoryName()` method. We couldn't find a way to access the category name of a triggered event.

**Comment by jcw9967** [comment]
Hey Joe (and friend)!

You're right that in 1.13.8 the BCEvent class doesn't supply a `getCategoryName()` method. This has been fixed in the 2.0.0 versions. You can take advantage of this using `compile 'com.bluecats:bluecats-android-sdk:2.0.0-rc-1'` if it's absolutely necessary, but we can't guarantee that the SDK is bug free as of yet as the release candidate isn't "publicly public".

Let me know if you've got any more questions!

**Comment by JrGoodle** [comment]
Ok, thanks for your quick response.

**Comment by kodalimanasa** [comment]
@jcw9967  hey its being hard to find " :bluecats-android-sdk:2.0.0 " can you give me the link to download 
thanks

**Comment by jcw9967** [comment]
The version is actually `2.0.0-rc-1`, and not just `2.0.0`. If you're still have issues with it, you can download the files [here](https://bintray.com/bluecats/maven/bluecats-android-sdk/2.0.0-rc-1/view#files/com/bluecats/bluecats-android-sdk/2.0.0-rc-1).

**Comment by caseycoding** [comment]
Quick note: properties such as `categoryName`, `categoryID`, `beaconID` etc. are slated for removal from the current iOS RC.  For the time being, it is better to use the `filteredMicroLocation` for category or beacon info.

**Comment by kodalimanasa** [comment]
Thanks for the quick reply and i don't see the way to get categoryName from getFilteredMicroLocation()

**Comment by jcw9967** [comment]
In 1.13.8 you can retrieve categories through the BCMicroLocation from the individual BCBeacons, BCSites, or through the `getCategoriesForSite()` method. Once you've got the BCCategory you can call `BCCategory.getName()` in order to get the name.

**Comment by kodalimanasa** [comment]
Sure Thanks

**Comment by JrGoodle** [comment]
We were able to get the category names of triggered events using microlocations on both iOS and Android. Thanks for all the help!
