### ISSUE TITLE
Error while making a release build

### ISSUE THREAD

**Issue by AlexxS** [bluecats/bluecats-android-sdk#9]
Hello, I've updated the SDK from about a very old(non-gradle, local libs) version to current gradle version 1.13.8, updated proguard-rules.pro, Gson library version is 2.4.0, 
classpath 'com.android.tools.build:gradle:2.1.2'

I receive an error while making a release build:
Error:warning: Ignoring InnerClasses attribute for an anonymous inner class
Error:(com.bluecats.sdk.ap) that doesn't come with an
Error:associated EnclosingMethod attribute. This class was probably produced by a
Error:compiler that did not target the modern .class file format. The recommended
Error:solution is to recompile the class from source, using an up-to-date compiler
Error:and without specifying any "-target" type options. The consequence of ignoring
Error:this warning is that reflective operations on this class will incorrectly
Error:indicate that it is _not_ an inner class.
Error:warning: Ignoring InnerClasses attribute for an anonymous inner class
Error:(com.bluecats.sdk.as) that doesn't come with an
Error:associated EnclosingMethod attribute. This class was probably produced by a
Error:compiler that did not target the modern .class file format. The recommended
Error:solution is to recompile the class from source, using an up-to-date compiler
Error:and without specifying any "-target" type options. The consequence of ignoring
Error:this warning is that reflective operations on this class will incorrectly
Error:indicate that it is _not_ an inner class.
Error:warning: Ignoring InnerClasses attribute for an anonymous inner class
Error:(com.bluecats.sdk.ar) that doesn't come with an
Error:associated EnclosingMethod attribute. This class was probably produced by a
Error:compiler that did not target the modern .class file format. The recommended
Error:solution is to recompile the class from source, using an up-to-date compiler
Error:and without specifying any "-target" type options. The consequence of ignoring
Error:this warning is that reflective operations on this class will incorrectly
Error:indicate that it is _not_ an inner class.
Error:warning: Ignoring InnerClasses attribute for an anonymous inner class
Error:(com.bluecats.sdk.at) that doesn't come with an
Error:associated EnclosingMethod attribute. This class was probably produced by a
Error:compiler that did not target the modern .class file format. The recommended
Error:solution is to recompile the class from source, using an up-to-date compiler
Error:and without specifying any "-target" type options. The consequence of ignoring
Error:this warning is that reflective operations on this class will incorrectly
Error:indicate that it is _not_ an inner class.
Error:warning: Ignoring InnerClasses attribute for an anonymous inner class
Error:(com.bluecats.sdk.au) that doesn't come with an
Error:associated EnclosingMethod attribute. This class was probably produced by a
Error:compiler that did not target the modern .class file format. The recommended
Error:solution is to recompile the class from source, using an up-to-date compiler
Error:and without specifying any "-target" type options. The consequence of ignoring
Error:this warning is that reflective operations on this class will incorrectly
Error:indicate that it is _not_ an inner class.
Error:warning: Ignoring InnerClasses attribute for an anonymous inner class
Error:(com.bluecats.sdk.aw) that doesn't come with an
Error:associated EnclosingMethod attribute. This class was probably produced by a
Error:compiler that did not target the modern .class file format. The recommended
Error:solution is to recompile the class from source, using an up-to-date compiler
Error:and without specifying any "-target" type options. The consequence of ignoring
Error:this warning is that reflective operations on this class will incorrectly
Error:indicate that it is _not_ an inner class.
Error:warning: Ignoring InnerClasses attribute for an anonymous inner class
Error:(com.bluecats.sdk.ax) that doesn't come with an
Error:associated EnclosingMethod attribute. This class was probably produced by a
Error:compiler that did not target the modern .class file format. The recommended
Error:solution is to recompile the class from source, using an up-to-date compiler
Error:and without specifying any "-target" type options. The consequence of ignoring
Error:this warning is that reflective operations on this class will incorrectly
Error:indicate that it is _not_ an inner class.
Error:warning: Ignoring InnerClasses attribute for an anonymous inner class
Error:(com.bluecats.sdk.av) that doesn't come with an
Error:associated EnclosingMethod attribute. This class was probably produced by a
Error:compiler that did not target the modern .class file format. The recommended
Error:solution is to recompile the class from source, using an up-to-date compiler
Error:and without specifying any "-target" type options. The consequence of ignoring
Error:this warning is that reflective operations on this class will incorrectly
Error:indicate that it is _not_ an inner class.
Error:warning: Ignoring InnerClasses attribute for an anonymous inner class
Error:(com.bluecats.sdk.aq) that doesn't come with an
Error:associated EnclosingMethod attribute. This class was probably produced by a
Error:compiler that did not target the modern .class file format. The recommended
Error:solution is to recompile the class from source, using an up-to-date compiler
Error:and without specifying any "-target" type options. The consequence of ignoring
Error:this warning is that reflective operations on this class will incorrectly
Error:indicate that it is _not_ an inner class.
Error:warning: Ignoring InnerClasses attribute for an anonymous inner class
Error:(com.bluecats.sdk.ay) that doesn't come with an
Error:associated EnclosingMethod attribute. This class was probably produced by a
Error:compiler that did not target the modern .class file format. The recommended
Error:solution is to recompile the class from source, using an up-to-date compiler
Error:and without specifying any "-target" type options. The consequence of ignoring
Error:this warning is that reflective operations on this class will incorrectly
Error:indicate that it is _not_ an inner class.
Error:warning: Ignoring InnerClasses attribute for an anonymous inner class
Error:(com.bluecats.sdk.az) that doesn't come with an
Error:associated EnclosingMethod attribute. This class was probably produced by a
Error:compiler that did not target the modern .class file format. The recommended
Error:solution is to recompile the class from source, using an up-to-date compiler
Error:and without specifying any "-target" type options. The consequence of ignoring
Error:this warning is that reflective operations on this class will incorrectly
Error:indicate that it is _not_ an inner class.
Error:UNEXPECTED TOP-LEVEL ERROR:
Error:java.lang.OutOfMemoryError: GC overhead limit exceeded
Error:  at java.util.Arrays.copyOfRange(Arrays.java:3664)
Error:  at java.lang.String.<init>(String.java:207)
Error:  at com.android.dx.rop.cst.CstString.utf8BytesToString(CstString.java:158)
Error:  at com.android.dx.rop.cst.CstString.<init>(CstString.java:200)
Error:  at com.android.dx.cf.cst.ConstantPoolParser.parseUtf8(ConstantPoolParser.java:371)
Error:  at com.android.dx.cf.cst.ConstantPoolParser.parse0(ConstantPoolParser.java:262)
Error:  at com.android.dx.cf.cst.ConstantPoolParser.parse(ConstantPoolParser.java:150)
Error:  at com.android.dx.cf.cst.ConstantPoolParser.parseIfNecessary(ConstantPoolParser.java:124)
Error:  at com.android.dx.cf.cst.ConstantPoolParser.getPool(ConstantPoolParser.java:115)
Error:  at com.android.dx.cf.direct.DirectClassFile.parse0(DirectClassFile.java:482)
Error:  at com.android.dx.cf.direct.DirectClassFile.parse(DirectClassFile.java:406)
Error:  at com.android.dx.cf.direct.DirectClassFile.parseToInterfacesIfNecessary(DirectClassFile.java:388)
Error:  at com.android.dx.cf.direct.DirectClassFile.getMagic(DirectClassFile.java:251)
Error:  at com.android.dx.command.dexer.Main.parseClass(Main.java:764)
Error:  at com.android.dx.command.dexer.Main.access$1500(Main.java:85)
Error:  at com.android.dx.command.dexer.Main$ClassParserTask.call(Main.java:1684)
Error:  at com.android.dx.command.dexer.Main.processClass(Main.java:749)
Error:  at com.android.dx.command.dexer.Main.processFileBytes(Main.java:718)
Error:  at com.android.dx.command.dexer.Main.access$1200(Main.java:85)
Error:  at com.android.dx.command.dexer.Main$FileBytesConsumer.processFileBytes(Main.java:1645)
Error:  at com.android.dx.cf.direct.ClassPathOpener.processArchive(ClassPathOpener.java:284)
Error:  at com.android.dx.cf.direct.ClassPathOpener.processOne(ClassPathOpener.java:166)
Error:  at com.android.dx.cf.direct.ClassPathOpener.process(ClassPathOpener.java:144)
Error:  at com.android.dx.command.dexer.Main.processOne(Main.java:672)
Error:  at com.android.dx.command.dexer.Main.processAllFiles(Main.java:569)
Error:  at com.android.dx.command.dexer.Main.runMultiDex(Main.java:366)
Error:  at com.android.dx.command.dexer.Main.run(Main.java:275)
Error:  at com.android.dx.command.dexer.Main.main(Main.java:245)
Error:  at com.android.dx.command.Main.main(Main.java:106)

**Comment by jcw9967** [comment]
Hey AlexxS!

That's odd that you're getting that error message. The previous `com.bluecats.sdk.xx` messages are what we get as well, but don't appear to cause any compilation errors. My first thought is that maybe there's an issue with your compilation options not supplying enough RAM to the build. Have a look [here](http://stackoverflow.com/questions/25013638/android-studio-google-jar-causing-gc-overhead-limit-exceeded-error) and get back to us! :)

**Comment by henrybluecats** [comment]
hey AlexxS,
We have released sdk v2.0.1, have you had a try?

**Comment by henrybluecats** [comment]
fixed.
